### ISSUE TITLE
Add footer to the website 

### ISSUE THREAD

**Issue by FidalMathew** [FidalMathew/apple.com#1]
![image](https://user-images.githubusercontent.com/84982038/135606478-8f2bfe73-4842-4f01-bf61-53b2bac03d40.png)

**Comment by Nutan2305** [comment]
I would like to work on this issue

**Comment by TheInspiredConjurer** [comment]
I'm new to open source. May I work on this for Hacktoberfest?

**Comment by FidalMathew** [comment]
@TheInspiredConjurer I would you to look for another issue in my other repositories. This issue is fixed.
