### ISSUE TITLE
Add Style to dropdown

### ISSUE THREAD

**Issue by FidalMathew** [FidalMathew/apple.com#2]
When the user clicks on the 'bag' icon, a dropdown appears.
The dropdown is not be styled in the PC version.
Add some styling similar to that of the mobile version of the same.
![image](https://user-images.githubusercontent.com/84982038/135606783-a8bff121-bac9-43c2-a107-cc545e4e7745.png)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please assign me this issue

**Comment by FidalMathew** [comment]
This issue has been fixed! Stay tuned for more issues
