### ISSUE TITLE
Website has nothing

### ISSUE THREAD

**Issue by RaviAnand111** [FidalMathew/apple.com#5]
There are no images and no footer to add on the website,  whose link in given in readme.md. 
Try to make the copy of apple.com.

**Comment by RaviAnand111** [comment]
Hey @FidalMathew  I created this issue, so I am working on it. Wherever you see this message just assign it to me. I will try to make a pr as soon as possible. Then you can review it. If you have anything to say. Kindly comment.

**Comment by RaviAnand111** [comment]
I just check all the images are corrupted, therefore they are not loading. I am working on it too.

**Comment by FidalMathew** [comment]
yeah sure !! Go for it!

**Comment by RaviAnand111** [comment]
hey @FidalMathew can you connect on discord, my  id is ->  ravi_anand#3909

**Comment by FidalMathew** [comment]
@RaviAnand111 sent
