### ISSUE TITLE
Website Image is corrupted

### ISSUE THREAD

**Issue by csachdeva83** [FidalMathew/apple.com#8]

**Comment by FidalMathew** [comment]
@csachdeva83 go ahead and work on the issue ;) . Do, deploy the forked project and send the link with the pull request.

**Comment by csachdeva83** [comment]
ok I will start right away

**Comment by csachdeva83** [comment]
I have fixed the issue please check it out

**Comment by FidalMathew** [comment]
@csachdeva83 Thank you for contributing 👍
